services:
  - type: web
    name: mlops-api-staging
    env: python
    plan: free
    branch: staging
    autoDeploy: true
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn apps.api.main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.4
      - key: MODEL_NAME
        value: fr2en-translator
      - key: MODEL_STAGE
        value: Staging
      - key: MLFLOW_TRACKING_URI
        sync: false
      - key: MLFLOW_TRACKING_USERNAME
        sync: false
      - key: MLFLOW_TRACKING_PASSWORD
        sync: false

  - type: web
    name: mlops-api-prod
    env: python
    plan: free
    branch: main
    autoDeploy: true
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn apps.api.main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.4
      - key: MODEL_NAME
        value: fr2en-translator
      - key: MODEL_STAGE
        value: Production
      - key: MLFLOW_TRACKING_URI
        sync: false
      - key: MLFLOW_TRACKING_USERNAME
        sync: false
      - key: MLFLOW_TRACKING_PASSWORD
        sync: false
